"""empty message

Revision ID: 1872bc7e6467
Revises: 4b6e661395a9
Create Date: 2022-08-12 03:05:36.531108

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1872bc7e6467'
down_revision = '4b6e661395a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('artist_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'artist', 'artist', ['artist_id'], ['id'])
    op.add_column('show', sa.Column('venue_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'show', 'venue', ['venue_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'show', type_='foreignkey')
    op.drop_column('show', 'venue_id')
    op.drop_constraint(None, 'artist', type_='foreignkey')
    op.drop_column('artist', 'artist_id')
    # ### end Alembic commands ###
