"""empty message

Revision ID: 4b6e661395a9
Revises: 1822b4c2db99
Create Date: 2022-08-11 20:00:36.604119

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b6e661395a9'
down_revision = '1822b4c2db99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('website_link', sa.String(length=120), nullable=True))
    op.drop_column('artist', 'website')
    op.add_column('venue', sa.Column('website_link', sa.String(length=120), nullable=True))
    op.add_column('venue', sa.Column('artist_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'venue', 'artist', ['artist_id'], ['id'])
    op.drop_column('venue', 'website')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venue', sa.Column('website', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'venue', type_='foreignkey')
    op.drop_column('venue', 'artist_id')
    op.drop_column('venue', 'website_link')
    op.add_column('artist', sa.Column('website', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.drop_column('artist', 'website_link')
    # ### end Alembic commands ###
