"""empty message

Revision ID: a94302ff0cc0
Revises: c520762719f6
Create Date: 2022-08-12 20:24:55.311732

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a94302ff0cc0'
down_revision = 'c520762719f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('genres', sa.String(length=120), nullable=True))
    op.drop_constraint('venue_artist_id_fkey', 'venue', type_='foreignkey')
    op.drop_column('venue', 'artist_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venue', sa.Column('artist_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('venue_artist_id_fkey', 'venue', 'artist', ['artist_id'], ['id'])
    op.drop_column('artist', 'genres')
    # ### end Alembic commands ###
