"""empty message

Revision ID: b223c8e312e0
Revises: 1b821e233cde
Create Date: 2022-08-12 09:26:41.127050

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b223c8e312e0'
down_revision = '1b821e233cde'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artist_genre_table',
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['artist.id'], ),
    sa.ForeignKeyConstraint(['genre_id'], ['genre.id'], ),
    sa.PrimaryKeyConstraint('genre_id', 'artist_id')
    )
    op.create_table('venue_genre_table',
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.Column('venue_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['genre_id'], ['genre.id'], ),
    sa.ForeignKeyConstraint(['venue_id'], ['venue.id'], ),
    sa.PrimaryKeyConstraint('genre_id', 'venue_id')
    )
    op.drop_table('venue_genre')
    op.drop_table('artist_genre')
    op.drop_constraint('artist_artist_id_fkey', 'artist', type_='foreignkey')
    op.drop_column('artist', 'artist_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('artist_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('artist_artist_id_fkey', 'artist', 'artist', ['artist_id'], ['id'])
    op.create_table('artist_genre',
    sa.Column('artist_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['artist.id'], name='artist_genre_artist_id_fkey')
    )
    op.create_table('venue_genre',
    sa.Column('venue_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['venue_id'], ['venue.id'], name='venue_genre_venue_id_fkey')
    )
    op.drop_table('venue_genre_table')
    op.drop_table('artist_genre_table')
    # ### end Alembic commands ###
